#!/usr/bin/env bash

kubectl create secret generic auth-server-config \
	--from-file=config-dev/auth-server/config.json \
	--from-file=config-dev/auth-server/auth-server.private.pem \
	--from-file=config-dev/auth-server/auth-server.public.pem

kubectl create secret generic profile-server-config \
	--from-file=config-dev/profile-server/config.json \
	--from-file=config-dev/profile-server/auth-server.public.pem

kubectl apply -f kubernetes
