#!/usr/bin/env bash

kubectl create secret generic auth-config \
	--from-file=config-dev/auth/config.json \
	--from-file=config-dev/auth/auth-server.private.pem \
	--from-file=config-dev/auth/auth-server.public.pem

kubectl create secret generic profile-config \
	--from-file=config-dev/profile/config.json \
	--from-file=config-dev/profile/auth-server.public.pem

kubectl apply -f kubernetes
