
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 4
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - image: chasemoskal/auth-server:latest
        imagePullPolicy: IfNotPresent
        name: auth
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: auth-config-volume
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: auth-config-volume
        secret:
          secretName: auth-config

---

apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
  - name: auth
    protocol: TCP
    port: 8000
    targetPort: 8000
