
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoback
  template:
    metadata:
      labels:
        app: demoback
    spec:
      containers:
      - image: chasemoskal/auth-server:latest
        imagePullPolicy: IfNotPresent
        name: auth-server
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: auth-server-config-volume
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: auth-server-config-volume
        secret:
          secretName: auth-server-config
