
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "workback.fullname" . }}-auth
spec:
  replicas: {{ .Values.microservices.auth.replicas }}
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
      annotations:
        checksum: {{ include (print $.Template.BasePath "/auth-config.yaml") . | sha256sum }}
    spec:
      containers:
      - image: {{ .Values.microservices.auth.image }}
        imagePullPolicy: IfNotPresent
        name: auth
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: auth-config-volume
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: auth-config-volume
        secret:
          secretName: {{ include "workback.fullname" . }}-auth-config
