
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "workback.fullname" . }}-profile
spec:
  replicas: {{ .Values.microservices.profile.replicas }}
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - image: {{ .Values.microservices.profile.image }}
        imagePullPolicy: IfNotPresent
        name: profile
        ports:
        - containerPort: 8001
        volumeMounts:
        - name: profile-config-volume
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: profile-config-volume
        secret:
          secretName: {{ include "workback.fullname" . }}-profile-config

---

apiVersion: v1
kind: Service
metadata:
  name: profile
spec:
  selector:
    app: profile
  ports:
  - name: profile
    protocol: TCP
    port: 8001
    targetPort: 8001

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workback.fullname" . }}-profile-config
type: Opaque
data:
{{ (.Files.Glob "config/profile/*").AsSecrets | indent 2 }}
